const hugo = {
    name: "Bink Starlek",
    class: "Ranger",
    subclass: "Beast Master",
    level: 4,
    pb: 2,
    alignment: 'Lawful good',
    proficiencies: {
        armor: ['Light', 'medium', 'shields'],
        weapons: ['simple', 'martial'],
        tools: ['Farm tools'],
        languages: ['common', 'elvish'],
        saving: ['str', 'dex', 'con'],
        skills: ['animal handling', 'athletics', 'insight', 'nature', 'perception', 'survival'],
    },
    race: 'Human (alt)',
    size: 'Medium',
    speed: 30,
    background: 'Farmer',
    gold: 5,
    silver: 0,
    copper: 0,
    hit_dice: 10,
    hp: 36,
    armor: 1,
    str: 15 + 1 + 2,
    dex: 12,
    con: 14 + 1 + 1,
    int: 10,
    wis: 13 + 1,
    cha: 8,
    feat: [
        {name: "Primeval Awareness", val: "Beginning at 3rd level, you can use your action and expend one ranger spell slot to focus your awareness on the region around you. For 1 minute per level of the spell slot you expend, you can sense whether the following types of creatures are present within 1 mile of you (or within up to 6 miles if you are in your favored terrain): aberrations, celestials, dragons, elementals, fey, fiends, and undead. This feature doesn’t reveal the creatures’ location or number."},
        { name: "Natural Explorer", val: "Also at 1st level, you are particularly familiar with one type of natural environment and are adept at traveling and surviving in such regions. Choose one type of favored terrain: arctic, coast, desert, forest, grassland, mountain, swamp, or the Underdark. When you make an Intelligence or Wisdom check related to your favored terrain, your proficiency bonus is doubled if you are using a skill that you’re proficient in.\nWhile traveling for an hour or more in your favored terrain, you gain the following benefits:\nDifficult terrain doesn’t slow your group’s travel.\nYour group can’t become lost except by magical means.\nEven when you are engaged in another activity while traveling (such as foraging, navigating, or tracking), you remain alert to danger.\nIf you are traveling alone, you can move stealthily at a normal pace.\nWhen you forage, you find twice as much food as you normally would.\nWhile tracking other creatures, you also learn their exact number, their sizes, and how long ago they passed through the area.\nYou choose additional favored terrain types at 6th and 10th level."},
        { name: "Favored Foe (Plants)", val: "This 1st-level feature replaces the Favored Enemy feature and works with the Foe Slayer feature. You gain no benefit from the replaced feature and don't qualify for anything in the game that requires it. \nWhen you hit a creature with an attack roll, you can call on your mystical bond with nature to mark the target as your favored enemy for 1 minute or until you lose your concentration (as if you were concentrating on a spell). \nThe first time on each of your turns that you hit the favored enemy and deal damage to it, including when you mark it, you increase that damage by 1d4. \nYou can use this feature to mark a favored enemy a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest. \nThis feature's extra damage increases when you reach certain levels in this class: to 1d6 at 6th level and to 1d8 at 14th level."},
        { name: "Ranger's Companion", val: "At 3rd level, you gain a beast companion that accompanies you on your adventures and is trained to fight alongside you. Choose a beast that is no larger than Medium and that has a challenge rating of 1/4 or lower (Player's Handbook Appendix D presents statistics for the hawk, mastiff, and panther as examples). Add your proficiency bonus to the beast’s AC, attack rolls, and damage rolls, as well as to any saving throws and skills it is proficient in. Its hit point maximum equals its normal maximum or four times your ranger level, whichever is higher. Like any creature, the beast can spend Hit Dice during a short rest. \nThe beast obeys your commands as best as it can. It takes its turn on your initiative. On your turn, you can verbally command the beast where to move (no action required by you). You can use your action to verbally command it to take the Attack, Dash, Disengage, or Help action. If you don’t issue a command, the beast takes the Dodge action. Once you have the Extra Attack feature, you can make one weapon attack yourself when you command the beast to take the Attack action. While traveling through your favored terrain with only the beast, you can move stealthily at a normal pace. \nIf you are incapacitated or absent, the beast acts on its own, focusing on protecting you and itself. The beast never requires your command to use its reaction, such as when making an opportunity attack. \nIf the beast dies, you can obtain another one by spending 8 hours magically bonding with another beast that isn’t hostile to you, either the same type of beast as before or a different one."},
        { name: "Resilient", val: "Choose one ability score (constitution). You gain the following benefits: \nIncrease the chosen ability score by 1, to a maximum of 20. \nYou gain proficiency in saving throws using the chosen ability."},
        { name: "Chef", val: "Time and effort spent mastering the culinary arts has paid off. You gain the following benefits: \nIncrease your Constitution or Wisdom score by 1, to a maximum of 20. \nYou gain proficiency with cook’s utensils if you don’t already have it.\nAs part of a short rest, you can cook special food, provided you have ingredients and cook's utensils on hand. You can prepare enough of this food for a number of creatures equal to 4 + your proficiency bonus. At the end of the short rest, any creature who eats the food and spends one or more Hit Dice to regain hit points regains an extra 1d8 hit points. \nWith one hour of work or when you finish a long rest, you can cook a number of treats equal to your proficiency bonus. These special treats last 8 hours after being made. A creature can use a bonus action to eat one of those treats to gain temporary hit points equal to your proficiency bonus."},
        { name: "Defense", val: "While you are wearing armor, you gain a +1 bonus to AC."},
    ],
    spells: {
        slots: [3],
        prepared: [],
        cantrips: [],
        lv1: [
            {
                name: 'Beast Bond',
                casting_time: '1 action',
                range: 'Touch',
                components: ['v', 's', 'm'],
                duration: 'Concentration, up to 10 minutes',
                val: "You establish a telepathic link with one beast you touch that is friendly to you or charmed by you. The spell fails if the beast’s Intelligence is 4 or higher. Until the spell ends, the link is active while you and the beast are within line of sight of each other. Through the link, the beast can understand your telepathic messages to it, and it can telepathically communicate simple emotions and concepts back to you. While the link is active, the beast gains advantage on attack rolls against any creature within 5 feet of you that you can see.",
            },
            {
                name: "Hunter's Mark",
                casting_time: '1 bonus action',
                range: '90 feet',
                components: ['v'],
                duration: 'Concentration, up to 1 hour',
                val: "You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack, and you have advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it. \nIf the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of yours to mark a new creature.",
                levels: "When you cast this spell using a spell slot of 3rd or 4th level, you can maintain your concentration on the spell for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain your concentration on the spell for up to 24 hours."
            },
            {
                name: "Entangle",
                casting_time: '1 action',
                range: '90 feet',
                components: ['v s'],
                duration: 'Concentration, up to 1 min',
                val: "Grasping weeds and vines sprout from the ground in a 20-foot square starting from a point within range. For the duration, these plants turn the ground in the area into difficult terrain. A creature in the area when you cast the spell must succeed on a Strength saving throw or be restrained by the entangling plants until the spell ends. A creature restrained by the plants can use its action to make a Strength check against your spell save DC. On a success, it frees itself. When the spell ends, the conjured plants wilt away.",
            },
        ],
        lv2: [],
        lv3: [],
        lv4: [],
        lv5: [],
        lv6: [],
        lv7: [],
        lv8: [],
        lv9: [],
        lv10: [],
    },
    equipment: [
        { name: "Pitchfork", val: "1d6 piercing. Thrown (20/60), versitile (1d8)"},
        { name: "5 GP of goods", val: "Wheet and potatos"},
        { name: "Leather armor", val: "+1 to AC"},
        { name: "Daggers x 2", val: "1d4 piercing. Finesse, light, thrown (20/60)"},
        { name: "Explorer's pack", val: ""},
        { name: "Longbow", val: "1d8 piercing (150/600)"},
        { name: "Arrows x 20", val: ""},
    ],
    familiar: {
    },
    story: {
        intro: "",
        background: "",
        personality: "",
        features: ""
    }

}

export default hugo